repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.255
    hooks:
      - id: ruff
        args: [--select=I001, --fix]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.11
