name: Documentation

on:
  workflow_dispatch:
  workflow_call:

env:
  HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

jobs:
  parse_commit_info:
    runs-on: ubuntu-latest
    outputs:
      deploy_to: ${{ steps.variables.outputs.deploy_to }}
      commit_title: ${{ steps.variables.outputs.commit_title }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy build utils
        run: |
          cp -r .github/utils ../utils

      - name: Decide where to deploy and create output variables
        id: variables
        run: |
          python ../utils/please.py set_deploy_to
          python ../utils/please.py set_commit_title

          echo github.ref ${{ github.ref }}

      - name: See outputs
        run: |
          echo 'deploy_to=${{ steps.variables.outputs.deploy_to }}'
          echo 'commit_title=${{ steps.variables.outputs.commit_title }}'

  build-documentation:
    runs-on: ubuntu-latest
    needs: parse_commit_info

    strategy:
      matrix:
        python-version: [3.13]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install a specific version of uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Create Virtual Environment
        run: uv venv --python ${{ matrix.python-version }}

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      - name: Install Package
        shell: bash
        run: |
          make doc-dependencies

      - name: Environment Information
        shell: bash
        run: |
          ls -la
          ls -la doc
          uv pip list

      - name: Build docs
        shell: bash
        run: |
          pushd doc; make doc; popd

      - name: Environment Information
        shell: bash
        run: |
          ls -la doc
          cat doc/_variables.yml
          ls -la doc/reference

      - name: Deploy to Documentation to a Branch
        uses: JamesIves/github-pages-deploy-action@v4
        if:  ${{ needs.parse_commit_info.outputs.deploy_to != '' }}
        with:
          folder: doc/_site
          branch: ${{ needs.parse_commit_info.outputs.deploy_to }}
          commit-message: ${{ needs.parse_commit_info.outputs.commit_title }}
